name = "navsite"
compatibility_date = "2026-1-6"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[env.production.vars]
GITHUB_CLIENT_ID = "Ov23li6YIJAT92bFNaqQ"
GITHUB_OWNER = "linkyneo"
GITHUB_REPO = "NavSite"
GITHUB_BRANCH = "main"
NEXTAUTH_URL = "https://navsite-5z4.pages.dev/api/auth"
NEXT_PUBLIC_API_URL="https://navsite-5z4.pages.dev"

